import Link from "next/link";
import "../globals.css";
import { Inter } from "next/font/google";
import { getPages } from "@/sanity/sanity_utils";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Manager Life",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto py-1">
        <header className="flex items-center justify-between">
          <Link href=" / ">
            <Image
              src="/TML_logo.png"
              width={250}
              height={200}
              alt="The Manager Life Logo"
              className="object-cover"
            />
          </Link>

          <div className="flex items-center gap-5 text-lg text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
            <Link href="/allBlogs">All Blog Post</Link>
          </div>
        </header>

        <main className="py-1">{children}</main>

        <footer className=" bg-sky-500/100 h-40 dark::bh-gray-900">
          <div className="grid grid-cols-2 gap-8 px-4 py-6 lg:py-8 md:grid-cols-4 text-md text-white">
            <Link className="hover:underline" href="/">
              HOME
            </Link>
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
            <Link className="hover:underline" href="/allBlogs">
              All Blog Post
            </Link>
            <Link className="hover:underline" href="/">
              Site Map
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
